### ISSUE TITLE
Link for type definitions for zip.js is dead

### ISSUE THREAD

**Issue by vperez-bg** [neodynamic/JSPrintManager-Angular#6]
The link in the documentation [https://github.com/slavovojacek/adbrain-typescript-definitions/blob/master/zip.js/zip.js.d.ts](url) is no longer available.  I'm trying to implement JSPrintManager for a React app that's in typescript.  Do you know where this can be found?

**Comment by neodynamic** [comment]
try this one https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/zip.js/index.d.ts
