### ISSUE TITLE
ERROR in src/app/app.component.ts:38:71

### ISSUE THREAD

**Issue by LeoLagardo** [neodynamic/JSPrintManager-Angular#7]
- error TS2339: Property 'Blocked' does not exist on type 'typeof WSStatus'.

38     } else if (JSPM.JSPrintManager.websocket_status === JSPM.WSStatus.Blocked) {

**Comment by neodynamic** [comment]
Thanks for reporting this. Just updated the scripts to JSPrintManager v3 so update them there
